### ISSUE TITLE
[feature] 提供api接口

### ISSUE THREAD

**Issue by CaoYunzhou** [lwydyby/poe-api#1]
我最近也在看这个逆向poe的代码，提供api是不是更方便

**Comment by lwydyby** [comment]
这个库我只想保持和https://github.com/ading2210/poe-api 一样的能力,你所说的api我理解是它上面一层的一种应用,有需要可以自己实现应该也很简单 比如:https://github.com/juzeon/poe-openai-proxy

**Comment by lwydyby** [comment]
换个说法就是,这个库只是一个内嵌的sdk,这个sdk你可以用于实现一个web-server也可以实现其他工具，这个工具可能不需要提供webserver.比如我实现的: https://github.com/lwydyby/mr-chglog

**Comment by CaoYunzhou** [comment]
> 换个说法就是,这个库只是一个内嵌的sdk,这个sdk你可以用于实现一个web-server也可以实现其他工具，这个工具可能不需要提供webserver.比如我实现的: https://github.com/lwydyby/mr-chglog

大佬，我借鉴了你的代码，稍微整合了下代码，用env和容器部署
https://github.com/CaoYunzhou/poe-openai-proxy
这样更容易小白一键部署使用

**Comment by CaoYunzhou** [comment]
后续应该会长期更新维护，添加标准header适配其他的开源项目使用
